[build]
  command = "npm run build"
  publish = "dist" # or "build" depending on your Vite output
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "vite"
  targetPort = 5173
  port = 8888
  autoLaunch = true